language: d
sudo: false
dist: trusty

services:
  - mongodb
  - redis-server

addons:
  apt:
    packages:
      - pkg-config
      - zlib1g-dev
      - libevent-dev
      - libssl-dev

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.078.0
  - dmd-2.073.2
  - ldc-1.7.0
  - ldc-1.6.0
  - ldc-1.5.0
  - ldc-1.4.0
  - ldc-1.3.0
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-beta

env:
  - VIBED_DRIVER=libevent PARTS=lint,builds,unittests,examples,tests
  - VIBED_DRIVER=vibe-core PARTS=builds,unittests,examples,tests
  - VIBED_DRIVER=libasync PARTS=builds,unittests

matrix:
  include:
    - d: dmd
      # https://issues.dlang.org/show_bug.cgi?id=13742
      env: DFLAGS="-cov -version=VibedSetCoverageMerge" DUB_BUILD_MODE="singleFile"
  exclude:
    - d: ldc-1.2.0
      env: VIBED_DRIVER=libasync PARTS=builds,unittests
  allow_failures:
    - d: dmd-beta
    - d: ldc-1.3.0
      env: VIBED_DRIVER=libasync PARTS=builds,unittests

before_install:
  - pyenv global system 3.6
  - pip3 install 'git+git://github.com/mesonbuild/meson.git@ca2db0f482e17b89d1b05ad056e4815bac4ad95d'

install:
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
  - export PATH=$PATH:$PWD/.ntmp

script: ./travis-ci.sh
after_success:
 - bash <(curl -s https://codecov.io/bash)
